groups:
  - name: emqx_go_alerts
    interval: 30s
    rules:
      # Node availability alerts
      - alert: EmqxNodeDown
        expr: up{job="emqx-go"} == 0
        for: 1m
        labels:
          severity: critical
          component: broker
        annotations:
          summary: "EMQX-Go node is down"
          description: "Node has been down for more than 1 minute."

      - alert: EmqxClusterDegraded
        expr: count(up{job="emqx-go"} == 1) < 3
        for: 2m
        labels:
          severity: warning
          component: cluster
        annotations:
          summary: "EMQX-Go cluster is degraded"
          description: "Less than 3 nodes are running."

      # Connection alerts
      - alert: HighConnectionCount
        expr: emqx_connections_count > 1000
        for: 5m
        labels:
          severity: warning
          component: connections
        annotations:
          summary: "High connection count detected"
          description: "Node has more than 1000 active connections."

      - alert: ConnectionSpike
        expr: rate(emqx_go_connections_total[5m]) > 100
        for: 2m
        labels:
          severity: warning
          component: connections
        annotations:
          summary: "Connection spike detected"
          description: "Receiving more than 100 new connections/sec."

      # Message throughput alerts
      - alert: HighMessageDropRate
        expr: rate(emqx_messages_dropped_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
          component: messaging
        annotations:
          summary: "High message drop rate"
          description: "Dropping more than 10 messages/sec."

      - alert: MessageDropRateCritical
        expr: rate(emqx_messages_dropped_total[5m]) > 100
        for: 1m
        labels:
          severity: critical
          component: messaging
        annotations:
          summary: "Critical message drop rate"
          description: "Dropping more than 100 messages/sec."

      # Session alerts
      - alert: HighSessionCount
        expr: emqx_sessions_count > 5000
        for: 5m
        labels:
          severity: warning
          component: sessions
        annotations:
          summary: "High session count"
          description: "More than 5000 active sessions."

      # Performance alerts
      - alert: PacketProcessingLag
        expr: rate(emqx_packets_received_total[5m]) - rate(emqx_packets_sent_total[5m]) > 1000
        for: 5m
        labels:
          severity: warning
          component: performance
        annotations:
          summary: "Packet processing lag detected"
          description: "Backlog of more than 1000 packets/sec."

      # Uptime alerts
      - alert: EmqxNodeRestarted
        expr: emqx_uptime_seconds < 300
        for: 1m
        labels:
          severity: info
          component: broker
        annotations:
          summary: "EMQX-Go node was recently restarted"
          description: "Node has been running for less than 5 minutes."
