apiVersion: v1
kind: Service
metadata:
  name: emqx-go-headless
spec:
  clusterIP: None # This makes the service "headless"
  ports:
  - port: 1883
    name: mqtt
  - port: 8081
    name: grpc
  selector:
    app: emqx-go