# k8s/pod.yaml
# A simple Kubernetes Pod definition for the EMQX-Go Broker PoC.

apiVersion: v1
kind: Pod
metadata:
  name: emqx-go-pod
  labels:
    app: emqx-go
spec:
  containers:
  - name: emqx-go
    # The image name should be replaced with the actual image built and pushed
    # to a container registry, e.g., "your-registry/emqx-go:latest".
    image: emqx-go:latest
    # We use "Never" for local testing with images built on the node.
    # In a real deployment, this would be "IfNotPresent" or "Always".
    imagePullPolicy: Never
    ports:
    - containerPort: 1883
      name: mqtt
      protocol: TCP