apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: emqx-pod-kill
  namespace: default
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: emqx-go
  scheduler:
    cron: '@every 5m'
  duration: '10s'
