apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: emqx-network-partition
  namespace: default
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      app: emqx-go
  direction: both
  target:
    mode: one
    selector:
      namespaces:
        - default
      labelSelectors:
        app: emqx-go
      podPhaseSelectors:
        - Running
  duration: '2m'
