apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: emqx-cpu-stress
  namespace: default
spec:
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: emqx-go
  stressors:
    cpu:
      workers: 2
      load: 80
  duration: '3m'
