apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: emqx-memory-stress
  namespace: default
spec:
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: emqx-go
  stressors:
    memory:
      workers: 4
      size: '512MB'
  duration: '3m'
