apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: emqx-io-stress
  namespace: default
spec:
  action: latency
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: emqx-go
  volumePath: /data
  path: '/data/**/*'
  delay: '100ms'
  percent: 50
  duration: '3m'
