// Code generated by protoc-gen-go. DO NOT EDIT.
// versions: protoc-gen-go vX.Y.Z, protoc vX.Y.Z
// source: proto/cluster.proto

package clusterpb

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// ---- 消息结构体示例 ----

type NodeInfo struct {
	NodeId    string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addr      string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Version   string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// ... (proto impl fields)
}

func (x *NodeInfo) Reset() { /* generated */ }
func (x *NodeInfo) String() string { /* generated */ }
func (*NodeInfo) ProtoMessage() {}
// getters...
func (x *NodeInfo) GetNodeId() string { if x!=nil { return x.NodeId }; return "" }

// 其他 message: JoinRequest, JoinResponse, Subscription, PublishForward, ...
